name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_HOME: /opt/maven
     # DOCKER_IMAGE: my-app
      NEXU_REPO_URL: "18.216.88.91:8081/repository/test"
      DOCKER_CLI_EXPERIMENTAL: "enabled"
   #   DOCKER_TLS_VERIFY: "0"
      DOCKER_CONTENT_TRUST: "0"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Unit Testing
      run: mvn test

    - name: Functional Testing
      run: mvn verify -DtestSuite=functional

    - name: Performance Testing
      run: mvn verify -DtestSuite=performance
      
    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=Argocd \
          -Dsonar.host.url=http://3.145.203.136:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Set up Docker daemon configuration for insecure registry
      run: |
        sudo mkdir -p /etc/docker
        echo '{"insecure-registries": ["18.216.88.91:9002"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Docker Login
      run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login 18.216.88.91:9002 -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin
 
    - name: Docker Build
      run: docker build -t nchandru360/gitactions/my-app:latest .
      
    - name: Docker Tag
      run: docker tag nchandru360/gitactions/my-app:latest 18.216.88.91:9002/repository/gitactions/my-app:latest
 
    - name: Docker Push to Nexus
      run: docker push 18.216.88.91:9002/repository/gitactions/my-app:latest
